#!/bin/bash 

g++ main.cpp \
    -ggdb \
    -I /usr/include/poppler \
    -lpoppler-cpp \
    -lpoppler \
    -lpoppler-dev \
    -lfreetype \
    -lpng \
    -lz \
    -lfontconfig \
    -ljpeg \
    -lcurl \
    -lsmime3 \
    -lnss3 \
    -lnspr4 \
    -lopenjp2 \
    -llcms2 \
    -ltiff \
    -o main

g++ testing.cpp \
    -ggdb \
    -I /usr/include/poppler \
    -lpoppler-cpp \
    -lpoppler \
    -lpoppler-dev \
    -lfreetype \
    -lpng \
    -lz \
    -lfontconfig \
    -ljpeg \
    -lcurl \
    -lsmime3 \
    -lnss3 \
    -lnspr4 \
    -lopenjp2 \
    -llcms2 \
    -ltiff \
    -o testing
